server:
  port: 8082
  
---
spring:
  profiles: local-mssql
  datasource:
    url: jdbc:mysql://localhost:3306/aviation?useSSL=false&user=root&password=root
    username: root
    password: root
    dbcp:
      max-active: 5
    tomcat:
      max-active: 5
 
---
server:
  context-path: /
---
spring:
  jpa:
    properties:
      hibernate.dialect:
        org.hibernate.dialect.MySQL5Dialect
---
spring:
  datasource:
    url:
      jdbc:mysql://localhost:3306/aviation?useSSL=false&user=root&password=root
---
spring:
  jpa:
    hibernate:
      ddl-auto: update
---
server:
  port: 8082       
